### ISSUE TITLE
UUID Support

### ISSUE THREAD

**Issue by rahul286** [rtCamp/amp-compatibility#115]
- [x] @dhaval-parekh adds the new field into BigQuery schema
- [x] @dhaval-parekh update node.js REST API so rather than the current "success" message, it returns "ampwp-{UUID}"
- [x] @dhaval-parekh skip the code responsible to delete past data for a site when new data is received via API 
- [x] @gagan0123 updates caching table which DataStudio interacts with
- [x] @pradeep910 create a new DataStudio report page to see all data in the system related to a UUID.  
- [x] @pradeep910 document the URL structure so from external system UUID based URLs can be created (same as site report)

**Comment by pradeep910** [comment]
@pdclark Here is the function to get limited urls from each CPT - https://github.com/ampproject/amp-wp/blob/89a22586151ee3b3acec3aa3fcca0049d158f2e3/src/Validation/ScannableURLProvider.php#L38-L116

cc @dhaval-parekh @rahul286

**Comment by dhaval-parekh** [comment]
The following points are completed in PR #117 And deployed on production.

- adds the new field into BigQuery schema
- update node.js REST API so rather than the current "success" message, it returns "ampwp-{UUID}"
- skip the code responsible to delete past data for a site when new data is received via API

cc: @gagan0123 , @pradeep910

**Comment by gagan0123** [comment]
Caching table created `cache_site_requests_errors` but its empty, because the new table that was created, `site_requests` is also empty. Once that is filled, only then we can add that caching table in Data Studio(its not allowing to make use of an empty table)
It is similar to `cache_sites_report` table with addition `site_requests`:
![image](https://user-images.githubusercontent.com/1535505/113101576-839f6b00-921a-11eb-967c-1c98b4a2216c.png)

@pradeep910

**Comment by pradeep910** [comment]
@gagan0123 I see the table without data still, so I will wait for the cache table data to come as we can't create report without data.

**Comment by rahul286** [comment]
@dhaval-parekh @gagan0123 as per last conversation, we will be using https://www.npmjs.com/package/uuid to generate UUID at node.js app level

Also, we will be using UUID v5 https://www.npmjs.com/package/uuid#uuidv5name-namespace-buffer-offset which uses SHA1 for reasons mentioned here https://rtcamp.slack.com/archives/G01E8C3JT45/p1617253407001300?thread_ts=1617207884.001000&cid=G01E8C3JT45

**Comment by pradeep910** [comment]
For UUID report - 

Need to replace the UUID in the highlighted part. In this URL `ampwp-111303a8-0a0d-561e-b002-90f465dd1225` is UUID.

datastudio.google.com/reporting/33e24fa4-a3e3-49ff-b2e1-8ba235a7424f/page/h2TAC?params=%7B%22df232%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580`ampwp-111303a8-0a0d-561e-b002-90f465dd1225`%22%7D
